# Site settings
title: Underduck
description: > # this means to ignore newlines until "baseurl:"
  Find exactly the playground you want.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  wachunga

page_gen:
  - data: 'playground'
    template: 'playground'
    name: 'name'
    dir: 'playgrounds'

# Build settings
markdown: kramdown
